// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow_serving/apis/classification.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "tensorflow_serving/apis/classification.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tensorflow {
namespace serving {
class ClassDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Class> {
} _Class_default_instance_;
class ClassificationsDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Classifications> {
} _Classifications_default_instance_;
class ClassificationResultDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ClassificationResult> {
} _ClassificationResult_default_instance_;
class ClassificationRequestDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ClassificationRequest> {
} _ClassificationRequest_default_instance_;
class ClassificationResponseDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ClassificationResponse> {
} _ClassificationResponse_default_instance_;

namespace protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[5];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Class, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Class, label_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Class, score_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Classifications, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Classifications, classes_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassificationResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassificationResult, classifications_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassificationRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassificationRequest, model_spec_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassificationRequest, input_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassificationResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClassificationResponse, result_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(Class)},
  { 6, -1, sizeof(Classifications)},
  { 11, -1, sizeof(ClassificationResult)},
  { 16, -1, sizeof(ClassificationRequest)},
  { 22, -1, sizeof(ClassificationResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Class_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Classifications_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_ClassificationResult_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_ClassificationRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_ClassificationResponse_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "tensorflow_serving/apis/classification.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

}  // namespace

void TableStruct::Shutdown() {
  _Class_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _Classifications_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _ClassificationResult_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _ClassificationRequest_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
  _ClassificationResponse_default_instance_.Shutdown();
  delete file_level_metadata[4].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::tensorflow::serving::protobuf_tensorflow_5fserving_2fapis_2finput_2eproto::InitDefaults();
  ::tensorflow::serving::protobuf_tensorflow_5fserving_2fapis_2fmodel_2eproto::InitDefaults();
  _Class_default_instance_.DefaultConstruct();
  _Classifications_default_instance_.DefaultConstruct();
  _ClassificationResult_default_instance_.DefaultConstruct();
  _ClassificationRequest_default_instance_.DefaultConstruct();
  _ClassificationResponse_default_instance_.DefaultConstruct();
  _ClassificationRequest_default_instance_.get_mutable()->model_spec_ = const_cast< ::tensorflow::serving::ModelSpec*>(
      ::tensorflow::serving::ModelSpec::internal_default_instance());
  _ClassificationRequest_default_instance_.get_mutable()->input_ = const_cast< ::tensorflow::serving::Input*>(
      ::tensorflow::serving::Input::internal_default_instance());
  _ClassificationResponse_default_instance_.get_mutable()->result_ = const_cast< ::tensorflow::serving::ClassificationResult*>(
      ::tensorflow::serving::ClassificationResult::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n,tensorflow_serving/apis/classification"
      ".proto\022\022tensorflow.serving\032#tensorflow_s"
      "erving/apis/input.proto\032#tensorflow_serv"
      "ing/apis/model.proto\"%\n\005Class\022\r\n\005label\030\001"
      " \001(\t\022\r\n\005score\030\002 \001(\002\"=\n\017Classifications\022*"
      "\n\007classes\030\001 \003(\0132\031.tensorflow.serving.Cla"
      "ss\"T\n\024ClassificationResult\022<\n\017classifica"
      "tions\030\001 \003(\0132#.tensorflow.serving.Classif"
      "ications\"t\n\025ClassificationRequest\0221\n\nmod"
      "el_spec\030\001 \001(\0132\035.tensorflow.serving.Model"
      "Spec\022(\n\005input\030\002 \001(\0132\031.tensorflow.serving"
      ".Input\"R\n\026ClassificationResponse\0228\n\006resu"
      "lt\030\001 \001(\0132(.tensorflow.serving.Classifica"
      "tionResultB\003\370\001\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 543);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tensorflow_serving/apis/classification.proto", &protobuf_RegisterTypes);
  ::tensorflow::serving::protobuf_tensorflow_5fserving_2fapis_2finput_2eproto::AddDescriptors();
  ::tensorflow::serving::protobuf_tensorflow_5fserving_2fapis_2fmodel_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Class::kLabelFieldNumber;
const int Class::kScoreFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Class::Class()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.serving.Class)
}
Class::Class(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena) {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::InitDefaults();
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.serving.Class)
}
Class::Class(const Class& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  label_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.label().size() > 0) {
    label_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.label(),
      GetArenaNoVirtual());
  }
  score_ = from.score_;
  // @@protoc_insertion_point(copy_constructor:tensorflow.serving.Class)
}

void Class::SharedCtor() {
  label_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  score_ = 0;
  _cached_size_ = 0;
}

Class::~Class() {
  // @@protoc_insertion_point(destructor:tensorflow.serving.Class)
  SharedDtor();
}

void Class::SharedDtor() {
  ::google::protobuf::Arena* arena = GetArenaNoVirtual();
  if (arena != NULL) {
    return;
  }

  label_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), arena);
}

void Class::ArenaDtor(void* object) {
  Class* _this = reinterpret_cast< Class* >(object);
  (void)_this;
}
void Class::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void Class::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Class::descriptor() {
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::file_level_metadata[0].descriptor;
}

const Class& Class::default_instance() {
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::InitDefaults();
  return *internal_default_instance();
}

Class* Class::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<Class>(arena);
}

void Class::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.serving.Class)
  label_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  score_ = 0;
}

bool Class::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.serving.Class)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string label = 1;
      case 1: {
        if (tag == 10u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_label()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->label().data(), this->label().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tensorflow.serving.Class.label"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float score = 2;
      case 2: {
        if (tag == 21u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &score_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.serving.Class)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.serving.Class)
  return false;
#undef DO_
}

void Class::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.serving.Class)
  // string label = 1;
  if (this->label().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->label().data(), this->label().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.serving.Class.label");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->label(), output);
  }

  // float score = 2;
  if (this->score() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->score(), output);
  }

  // @@protoc_insertion_point(serialize_end:tensorflow.serving.Class)
}

::google::protobuf::uint8* Class::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.serving.Class)
  // string label = 1;
  if (this->label().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->label().data(), this->label().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.serving.Class.label");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->label(), target);
  }

  // float score = 2;
  if (this->score() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->score(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.serving.Class)
  return target;
}

size_t Class::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.serving.Class)
  size_t total_size = 0;

  // string label = 1;
  if (this->label().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->label());
  }

  // float score = 2;
  if (this->score() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Class::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tensorflow.serving.Class)
  GOOGLE_DCHECK_NE(&from, this);
  const Class* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Class>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tensorflow.serving.Class)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tensorflow.serving.Class)
    MergeFrom(*source);
  }
}

void Class::MergeFrom(const Class& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.serving.Class)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.label().size() > 0) {
    set_label(from.label());
  }
  if (from.score() != 0) {
    set_score(from.score());
  }
}

void Class::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tensorflow.serving.Class)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Class::CopyFrom(const Class& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.serving.Class)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Class::IsInitialized() const {
  return true;
}

void Class::Swap(Class* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    Class* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void Class::UnsafeArenaSwap(Class* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void Class::InternalSwap(Class* other) {
  label_.Swap(&other->label_);
  std::swap(score_, other->score_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Class::GetMetadata() const {
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Class

// string label = 1;
void Class::clear_label() {
  label_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
const ::std::string& Class::label() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.Class.label)
  return label_.Get();
}
void Class::set_label(const ::std::string& value) {
  
  label_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:tensorflow.serving.Class.label)
}
void Class::set_label(const char* value) {
  
  label_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:tensorflow.serving.Class.label)
}
void Class::set_label(const char* value,
    size_t size) {
  
  label_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:tensorflow.serving.Class.label)
}
::std::string* Class::mutable_label() {
  
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.Class.label)
  return label_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
::std::string* Class::release_label() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.Class.label)
  
  return label_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
::std::string* Class::unsafe_arena_release_label() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.serving.Class.label)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return label_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
void Class::set_allocated_label(::std::string* label) {
  if (label != NULL) {
    
  } else {
    
  }
  label_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), label,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.Class.label)
}
void Class::unsafe_arena_set_allocated_label(
    ::std::string* label) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (label != NULL) {
    
  } else {
    
  }
  label_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      label, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.Class.label)
}

// float score = 2;
void Class::clear_score() {
  score_ = 0;
}
float Class::score() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.Class.score)
  return score_;
}
void Class::set_score(float value) {
  
  score_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.serving.Class.score)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Classifications::kClassesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Classifications::Classifications()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.serving.Classifications)
}
Classifications::Classifications(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena),
  classes_(arena) {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::InitDefaults();
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.serving.Classifications)
}
Classifications::Classifications(const Classifications& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      classes_(from.classes_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:tensorflow.serving.Classifications)
}

void Classifications::SharedCtor() {
  _cached_size_ = 0;
}

Classifications::~Classifications() {
  // @@protoc_insertion_point(destructor:tensorflow.serving.Classifications)
  SharedDtor();
}

void Classifications::SharedDtor() {
  ::google::protobuf::Arena* arena = GetArenaNoVirtual();
  if (arena != NULL) {
    return;
  }

}

void Classifications::ArenaDtor(void* object) {
  Classifications* _this = reinterpret_cast< Classifications* >(object);
  (void)_this;
}
void Classifications::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void Classifications::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Classifications::descriptor() {
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::file_level_metadata[1].descriptor;
}

const Classifications& Classifications::default_instance() {
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::InitDefaults();
  return *internal_default_instance();
}

Classifications* Classifications::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<Classifications>(arena);
}

void Classifications::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.serving.Classifications)
  classes_.Clear();
}

bool Classifications::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.serving.Classifications)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .tensorflow.serving.Class classes = 1;
      case 1: {
        if (tag == 10u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_classes()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.serving.Classifications)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.serving.Classifications)
  return false;
#undef DO_
}

void Classifications::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.serving.Classifications)
  // repeated .tensorflow.serving.Class classes = 1;
  for (unsigned int i = 0, n = this->classes_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->classes(i), output);
  }

  // @@protoc_insertion_point(serialize_end:tensorflow.serving.Classifications)
}

::google::protobuf::uint8* Classifications::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.serving.Classifications)
  // repeated .tensorflow.serving.Class classes = 1;
  for (unsigned int i = 0, n = this->classes_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->classes(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.serving.Classifications)
  return target;
}

size_t Classifications::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.serving.Classifications)
  size_t total_size = 0;

  // repeated .tensorflow.serving.Class classes = 1;
  {
    unsigned int count = this->classes_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->classes(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Classifications::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tensorflow.serving.Classifications)
  GOOGLE_DCHECK_NE(&from, this);
  const Classifications* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Classifications>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tensorflow.serving.Classifications)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tensorflow.serving.Classifications)
    MergeFrom(*source);
  }
}

void Classifications::MergeFrom(const Classifications& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.serving.Classifications)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  classes_.MergeFrom(from.classes_);
}

void Classifications::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tensorflow.serving.Classifications)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Classifications::CopyFrom(const Classifications& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.serving.Classifications)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Classifications::IsInitialized() const {
  return true;
}

void Classifications::Swap(Classifications* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    Classifications* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void Classifications::UnsafeArenaSwap(Classifications* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void Classifications::InternalSwap(Classifications* other) {
  classes_.UnsafeArenaSwap(&other->classes_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Classifications::GetMetadata() const {
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Classifications

// repeated .tensorflow.serving.Class classes = 1;
int Classifications::classes_size() const {
  return classes_.size();
}
void Classifications::clear_classes() {
  classes_.Clear();
}
const ::tensorflow::serving::Class& Classifications::classes(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.Classifications.classes)
  return classes_.Get(index);
}
::tensorflow::serving::Class* Classifications::mutable_classes(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.Classifications.classes)
  return classes_.Mutable(index);
}
::tensorflow::serving::Class* Classifications::add_classes() {
  // @@protoc_insertion_point(field_add:tensorflow.serving.Classifications.classes)
  return classes_.Add();
}
::google::protobuf::RepeatedPtrField< ::tensorflow::serving::Class >*
Classifications::mutable_classes() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.serving.Classifications.classes)
  return &classes_;
}
const ::google::protobuf::RepeatedPtrField< ::tensorflow::serving::Class >&
Classifications::classes() const {
  // @@protoc_insertion_point(field_list:tensorflow.serving.Classifications.classes)
  return classes_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClassificationResult::kClassificationsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClassificationResult::ClassificationResult()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.serving.ClassificationResult)
}
ClassificationResult::ClassificationResult(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena),
  classifications_(arena) {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::InitDefaults();
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.serving.ClassificationResult)
}
ClassificationResult::ClassificationResult(const ClassificationResult& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      classifications_(from.classifications_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:tensorflow.serving.ClassificationResult)
}

void ClassificationResult::SharedCtor() {
  _cached_size_ = 0;
}

ClassificationResult::~ClassificationResult() {
  // @@protoc_insertion_point(destructor:tensorflow.serving.ClassificationResult)
  SharedDtor();
}

void ClassificationResult::SharedDtor() {
  ::google::protobuf::Arena* arena = GetArenaNoVirtual();
  if (arena != NULL) {
    return;
  }

}

void ClassificationResult::ArenaDtor(void* object) {
  ClassificationResult* _this = reinterpret_cast< ClassificationResult* >(object);
  (void)_this;
}
void ClassificationResult::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void ClassificationResult::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClassificationResult::descriptor() {
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::file_level_metadata[2].descriptor;
}

const ClassificationResult& ClassificationResult::default_instance() {
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::InitDefaults();
  return *internal_default_instance();
}

ClassificationResult* ClassificationResult::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<ClassificationResult>(arena);
}

void ClassificationResult::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.serving.ClassificationResult)
  classifications_.Clear();
}

bool ClassificationResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.serving.ClassificationResult)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .tensorflow.serving.Classifications classifications = 1;
      case 1: {
        if (tag == 10u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_classifications()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.serving.ClassificationResult)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.serving.ClassificationResult)
  return false;
#undef DO_
}

void ClassificationResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.serving.ClassificationResult)
  // repeated .tensorflow.serving.Classifications classifications = 1;
  for (unsigned int i = 0, n = this->classifications_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->classifications(i), output);
  }

  // @@protoc_insertion_point(serialize_end:tensorflow.serving.ClassificationResult)
}

::google::protobuf::uint8* ClassificationResult::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.serving.ClassificationResult)
  // repeated .tensorflow.serving.Classifications classifications = 1;
  for (unsigned int i = 0, n = this->classifications_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->classifications(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.serving.ClassificationResult)
  return target;
}

size_t ClassificationResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.serving.ClassificationResult)
  size_t total_size = 0;

  // repeated .tensorflow.serving.Classifications classifications = 1;
  {
    unsigned int count = this->classifications_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->classifications(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClassificationResult::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tensorflow.serving.ClassificationResult)
  GOOGLE_DCHECK_NE(&from, this);
  const ClassificationResult* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ClassificationResult>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tensorflow.serving.ClassificationResult)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tensorflow.serving.ClassificationResult)
    MergeFrom(*source);
  }
}

void ClassificationResult::MergeFrom(const ClassificationResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.serving.ClassificationResult)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  classifications_.MergeFrom(from.classifications_);
}

void ClassificationResult::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tensorflow.serving.ClassificationResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClassificationResult::CopyFrom(const ClassificationResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.serving.ClassificationResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClassificationResult::IsInitialized() const {
  return true;
}

void ClassificationResult::Swap(ClassificationResult* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    ClassificationResult* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void ClassificationResult::UnsafeArenaSwap(ClassificationResult* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void ClassificationResult::InternalSwap(ClassificationResult* other) {
  classifications_.UnsafeArenaSwap(&other->classifications_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ClassificationResult::GetMetadata() const {
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::file_level_metadata[2];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ClassificationResult

// repeated .tensorflow.serving.Classifications classifications = 1;
int ClassificationResult::classifications_size() const {
  return classifications_.size();
}
void ClassificationResult::clear_classifications() {
  classifications_.Clear();
}
const ::tensorflow::serving::Classifications& ClassificationResult::classifications(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.ClassificationResult.classifications)
  return classifications_.Get(index);
}
::tensorflow::serving::Classifications* ClassificationResult::mutable_classifications(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.ClassificationResult.classifications)
  return classifications_.Mutable(index);
}
::tensorflow::serving::Classifications* ClassificationResult::add_classifications() {
  // @@protoc_insertion_point(field_add:tensorflow.serving.ClassificationResult.classifications)
  return classifications_.Add();
}
::google::protobuf::RepeatedPtrField< ::tensorflow::serving::Classifications >*
ClassificationResult::mutable_classifications() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.serving.ClassificationResult.classifications)
  return &classifications_;
}
const ::google::protobuf::RepeatedPtrField< ::tensorflow::serving::Classifications >&
ClassificationResult::classifications() const {
  // @@protoc_insertion_point(field_list:tensorflow.serving.ClassificationResult.classifications)
  return classifications_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

void ClassificationRequest::_slow_mutable_model_spec() {
  model_spec_ = ::google::protobuf::Arena::CreateMessage< ::tensorflow::serving::ModelSpec >(
      GetArenaNoVirtual());
}
::tensorflow::serving::ModelSpec* ClassificationRequest::_slow_release_model_spec() {
  if (model_spec_ == NULL) {
    return NULL;
  } else {
    ::tensorflow::serving::ModelSpec* temp = new ::tensorflow::serving::ModelSpec(*model_spec_);
    model_spec_ = NULL;
    return temp;
  }
}
::tensorflow::serving::ModelSpec* ClassificationRequest::unsafe_arena_release_model_spec() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.serving.ClassificationRequest.model_spec)
  
  ::tensorflow::serving::ModelSpec* temp = model_spec_;
  model_spec_ = NULL;
  return temp;
}
void ClassificationRequest::_slow_set_allocated_model_spec(
    ::google::protobuf::Arena* message_arena, ::tensorflow::serving::ModelSpec** model_spec) {
    if (message_arena != NULL && 
        ::google::protobuf::Arena::GetArena(*model_spec) == NULL) {
      message_arena->Own(*model_spec);
    } else if (message_arena !=
               ::google::protobuf::Arena::GetArena(*model_spec)) {
      ::tensorflow::serving::ModelSpec* new_model_spec = 
            ::google::protobuf::Arena::CreateMessage< ::tensorflow::serving::ModelSpec >(
            message_arena);
      new_model_spec->CopyFrom(**model_spec);
      *model_spec = new_model_spec;
    }
}
void ClassificationRequest::unsafe_arena_set_allocated_model_spec(
    ::tensorflow::serving::ModelSpec* model_spec) {
  if (GetArenaNoVirtual() == NULL) {
    delete model_spec_;
  }
  model_spec_ = model_spec;
  if (model_spec) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.ClassificationRequest.model_spec)
}
void ClassificationRequest::_slow_mutable_input() {
  input_ = ::google::protobuf::Arena::CreateMessage< ::tensorflow::serving::Input >(
      GetArenaNoVirtual());
}
::tensorflow::serving::Input* ClassificationRequest::_slow_release_input() {
  if (input_ == NULL) {
    return NULL;
  } else {
    ::tensorflow::serving::Input* temp = new ::tensorflow::serving::Input(*input_);
    input_ = NULL;
    return temp;
  }
}
::tensorflow::serving::Input* ClassificationRequest::unsafe_arena_release_input() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.serving.ClassificationRequest.input)
  
  ::tensorflow::serving::Input* temp = input_;
  input_ = NULL;
  return temp;
}
void ClassificationRequest::_slow_set_allocated_input(
    ::google::protobuf::Arena* message_arena, ::tensorflow::serving::Input** input) {
    if (message_arena != NULL && 
        ::google::protobuf::Arena::GetArena(*input) == NULL) {
      message_arena->Own(*input);
    } else if (message_arena !=
               ::google::protobuf::Arena::GetArena(*input)) {
      ::tensorflow::serving::Input* new_input = 
            ::google::protobuf::Arena::CreateMessage< ::tensorflow::serving::Input >(
            message_arena);
      new_input->CopyFrom(**input);
      *input = new_input;
    }
}
void ClassificationRequest::unsafe_arena_set_allocated_input(
    ::tensorflow::serving::Input* input) {
  if (GetArenaNoVirtual() == NULL) {
    delete input_;
  }
  input_ = input;
  if (input) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.ClassificationRequest.input)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClassificationRequest::kModelSpecFieldNumber;
const int ClassificationRequest::kInputFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClassificationRequest::ClassificationRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.serving.ClassificationRequest)
}
ClassificationRequest::ClassificationRequest(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena) {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::InitDefaults();
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.serving.ClassificationRequest)
}
ClassificationRequest::ClassificationRequest(const ClassificationRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_model_spec()) {
    model_spec_ = new ::tensorflow::serving::ModelSpec(*from.model_spec_);
  } else {
    model_spec_ = NULL;
  }
  if (from.has_input()) {
    input_ = new ::tensorflow::serving::Input(*from.input_);
  } else {
    input_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:tensorflow.serving.ClassificationRequest)
}

void ClassificationRequest::SharedCtor() {
  ::memset(&model_spec_, 0, reinterpret_cast<char*>(&input_) -
    reinterpret_cast<char*>(&model_spec_) + sizeof(input_));
  _cached_size_ = 0;
}

ClassificationRequest::~ClassificationRequest() {
  // @@protoc_insertion_point(destructor:tensorflow.serving.ClassificationRequest)
  SharedDtor();
}

void ClassificationRequest::SharedDtor() {
  ::google::protobuf::Arena* arena = GetArenaNoVirtual();
  if (arena != NULL) {
    return;
  }

  if (this != internal_default_instance()) {
    delete model_spec_;
  }
  if (this != internal_default_instance()) {
    delete input_;
  }
}

void ClassificationRequest::ArenaDtor(void* object) {
  ClassificationRequest* _this = reinterpret_cast< ClassificationRequest* >(object);
  (void)_this;
}
void ClassificationRequest::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void ClassificationRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClassificationRequest::descriptor() {
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::file_level_metadata[3].descriptor;
}

const ClassificationRequest& ClassificationRequest::default_instance() {
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::InitDefaults();
  return *internal_default_instance();
}

ClassificationRequest* ClassificationRequest::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<ClassificationRequest>(arena);
}

void ClassificationRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.serving.ClassificationRequest)
  if (GetArenaNoVirtual() == NULL && model_spec_ != NULL) {
    delete model_spec_;
  }
  model_spec_ = NULL;
  if (GetArenaNoVirtual() == NULL && input_ != NULL) {
    delete input_;
  }
  input_ = NULL;
}

bool ClassificationRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.serving.ClassificationRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .tensorflow.serving.ModelSpec model_spec = 1;
      case 1: {
        if (tag == 10u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_model_spec()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .tensorflow.serving.Input input = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_input()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.serving.ClassificationRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.serving.ClassificationRequest)
  return false;
#undef DO_
}

void ClassificationRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.serving.ClassificationRequest)
  // .tensorflow.serving.ModelSpec model_spec = 1;
  if (this->has_model_spec()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->model_spec_, output);
  }

  // .tensorflow.serving.Input input = 2;
  if (this->has_input()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->input_, output);
  }

  // @@protoc_insertion_point(serialize_end:tensorflow.serving.ClassificationRequest)
}

::google::protobuf::uint8* ClassificationRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.serving.ClassificationRequest)
  // .tensorflow.serving.ModelSpec model_spec = 1;
  if (this->has_model_spec()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->model_spec_, false, target);
  }

  // .tensorflow.serving.Input input = 2;
  if (this->has_input()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->input_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.serving.ClassificationRequest)
  return target;
}

size_t ClassificationRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.serving.ClassificationRequest)
  size_t total_size = 0;

  // .tensorflow.serving.ModelSpec model_spec = 1;
  if (this->has_model_spec()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->model_spec_);
  }

  // .tensorflow.serving.Input input = 2;
  if (this->has_input()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->input_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClassificationRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tensorflow.serving.ClassificationRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ClassificationRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ClassificationRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tensorflow.serving.ClassificationRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tensorflow.serving.ClassificationRequest)
    MergeFrom(*source);
  }
}

void ClassificationRequest::MergeFrom(const ClassificationRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.serving.ClassificationRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_model_spec()) {
    mutable_model_spec()->::tensorflow::serving::ModelSpec::MergeFrom(from.model_spec());
  }
  if (from.has_input()) {
    mutable_input()->::tensorflow::serving::Input::MergeFrom(from.input());
  }
}

void ClassificationRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tensorflow.serving.ClassificationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClassificationRequest::CopyFrom(const ClassificationRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.serving.ClassificationRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClassificationRequest::IsInitialized() const {
  return true;
}

void ClassificationRequest::Swap(ClassificationRequest* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    ClassificationRequest* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void ClassificationRequest::UnsafeArenaSwap(ClassificationRequest* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void ClassificationRequest::InternalSwap(ClassificationRequest* other) {
  std::swap(model_spec_, other->model_spec_);
  std::swap(input_, other->input_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ClassificationRequest::GetMetadata() const {
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::file_level_metadata[3];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ClassificationRequest

// .tensorflow.serving.ModelSpec model_spec = 1;
bool ClassificationRequest::has_model_spec() const {
  return this != internal_default_instance() && model_spec_ != NULL;
}
void ClassificationRequest::clear_model_spec() {
  if (GetArenaNoVirtual() == NULL && model_spec_ != NULL) delete model_spec_;
  model_spec_ = NULL;
}
const ::tensorflow::serving::ModelSpec& ClassificationRequest::model_spec() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.ClassificationRequest.model_spec)
  return model_spec_ != NULL ? *model_spec_
                         : *::tensorflow::serving::ModelSpec::internal_default_instance();
}
::tensorflow::serving::ModelSpec* ClassificationRequest::mutable_model_spec() {
  
  if (model_spec_ == NULL) {
    _slow_mutable_model_spec();
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.ClassificationRequest.model_spec)
  return model_spec_;
}
::tensorflow::serving::ModelSpec* ClassificationRequest::release_model_spec() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.ClassificationRequest.model_spec)
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_model_spec();
  } else {
    ::tensorflow::serving::ModelSpec* temp = model_spec_;
    model_spec_ = NULL;
    return temp;
  }
}
 void ClassificationRequest::set_allocated_model_spec(::tensorflow::serving::ModelSpec* model_spec) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete model_spec_;
  }
  if (model_spec != NULL) {
    _slow_set_allocated_model_spec(message_arena, &model_spec);
  }
  model_spec_ = model_spec;
  if (model_spec) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.ClassificationRequest.model_spec)
}

// .tensorflow.serving.Input input = 2;
bool ClassificationRequest::has_input() const {
  return this != internal_default_instance() && input_ != NULL;
}
void ClassificationRequest::clear_input() {
  if (GetArenaNoVirtual() == NULL && input_ != NULL) delete input_;
  input_ = NULL;
}
const ::tensorflow::serving::Input& ClassificationRequest::input() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.ClassificationRequest.input)
  return input_ != NULL ? *input_
                         : *::tensorflow::serving::Input::internal_default_instance();
}
::tensorflow::serving::Input* ClassificationRequest::mutable_input() {
  
  if (input_ == NULL) {
    _slow_mutable_input();
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.ClassificationRequest.input)
  return input_;
}
::tensorflow::serving::Input* ClassificationRequest::release_input() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.ClassificationRequest.input)
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_input();
  } else {
    ::tensorflow::serving::Input* temp = input_;
    input_ = NULL;
    return temp;
  }
}
 void ClassificationRequest::set_allocated_input(::tensorflow::serving::Input* input) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete input_;
  }
  if (input != NULL) {
    _slow_set_allocated_input(message_arena, &input);
  }
  input_ = input;
  if (input) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.ClassificationRequest.input)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

void ClassificationResponse::_slow_mutable_result() {
  result_ = ::google::protobuf::Arena::CreateMessage< ::tensorflow::serving::ClassificationResult >(
      GetArenaNoVirtual());
}
::tensorflow::serving::ClassificationResult* ClassificationResponse::_slow_release_result() {
  if (result_ == NULL) {
    return NULL;
  } else {
    ::tensorflow::serving::ClassificationResult* temp = new ::tensorflow::serving::ClassificationResult(*result_);
    result_ = NULL;
    return temp;
  }
}
::tensorflow::serving::ClassificationResult* ClassificationResponse::unsafe_arena_release_result() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.serving.ClassificationResponse.result)
  
  ::tensorflow::serving::ClassificationResult* temp = result_;
  result_ = NULL;
  return temp;
}
void ClassificationResponse::_slow_set_allocated_result(
    ::google::protobuf::Arena* message_arena, ::tensorflow::serving::ClassificationResult** result) {
    if (message_arena != NULL && 
        ::google::protobuf::Arena::GetArena(*result) == NULL) {
      message_arena->Own(*result);
    } else if (message_arena !=
               ::google::protobuf::Arena::GetArena(*result)) {
      ::tensorflow::serving::ClassificationResult* new_result = 
            ::google::protobuf::Arena::CreateMessage< ::tensorflow::serving::ClassificationResult >(
            message_arena);
      new_result->CopyFrom(**result);
      *result = new_result;
    }
}
void ClassificationResponse::unsafe_arena_set_allocated_result(
    ::tensorflow::serving::ClassificationResult* result) {
  if (GetArenaNoVirtual() == NULL) {
    delete result_;
  }
  result_ = result;
  if (result) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.ClassificationResponse.result)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClassificationResponse::kResultFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClassificationResponse::ClassificationResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.serving.ClassificationResponse)
}
ClassificationResponse::ClassificationResponse(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena) {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::InitDefaults();
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.serving.ClassificationResponse)
}
ClassificationResponse::ClassificationResponse(const ClassificationResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_result()) {
    result_ = new ::tensorflow::serving::ClassificationResult(*from.result_);
  } else {
    result_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:tensorflow.serving.ClassificationResponse)
}

void ClassificationResponse::SharedCtor() {
  result_ = NULL;
  _cached_size_ = 0;
}

ClassificationResponse::~ClassificationResponse() {
  // @@protoc_insertion_point(destructor:tensorflow.serving.ClassificationResponse)
  SharedDtor();
}

void ClassificationResponse::SharedDtor() {
  ::google::protobuf::Arena* arena = GetArenaNoVirtual();
  if (arena != NULL) {
    return;
  }

  if (this != internal_default_instance()) {
    delete result_;
  }
}

void ClassificationResponse::ArenaDtor(void* object) {
  ClassificationResponse* _this = reinterpret_cast< ClassificationResponse* >(object);
  (void)_this;
}
void ClassificationResponse::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void ClassificationResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClassificationResponse::descriptor() {
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::file_level_metadata[4].descriptor;
}

const ClassificationResponse& ClassificationResponse::default_instance() {
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::InitDefaults();
  return *internal_default_instance();
}

ClassificationResponse* ClassificationResponse::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<ClassificationResponse>(arena);
}

void ClassificationResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.serving.ClassificationResponse)
  if (GetArenaNoVirtual() == NULL && result_ != NULL) {
    delete result_;
  }
  result_ = NULL;
}

bool ClassificationResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.serving.ClassificationResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .tensorflow.serving.ClassificationResult result = 1;
      case 1: {
        if (tag == 10u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_result()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.serving.ClassificationResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.serving.ClassificationResponse)
  return false;
#undef DO_
}

void ClassificationResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.serving.ClassificationResponse)
  // .tensorflow.serving.ClassificationResult result = 1;
  if (this->has_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->result_, output);
  }

  // @@protoc_insertion_point(serialize_end:tensorflow.serving.ClassificationResponse)
}

::google::protobuf::uint8* ClassificationResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.serving.ClassificationResponse)
  // .tensorflow.serving.ClassificationResult result = 1;
  if (this->has_result()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->result_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.serving.ClassificationResponse)
  return target;
}

size_t ClassificationResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.serving.ClassificationResponse)
  size_t total_size = 0;

  // .tensorflow.serving.ClassificationResult result = 1;
  if (this->has_result()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->result_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClassificationResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tensorflow.serving.ClassificationResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ClassificationResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ClassificationResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tensorflow.serving.ClassificationResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tensorflow.serving.ClassificationResponse)
    MergeFrom(*source);
  }
}

void ClassificationResponse::MergeFrom(const ClassificationResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.serving.ClassificationResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_result()) {
    mutable_result()->::tensorflow::serving::ClassificationResult::MergeFrom(from.result());
  }
}

void ClassificationResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tensorflow.serving.ClassificationResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClassificationResponse::CopyFrom(const ClassificationResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.serving.ClassificationResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClassificationResponse::IsInitialized() const {
  return true;
}

void ClassificationResponse::Swap(ClassificationResponse* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    ClassificationResponse* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void ClassificationResponse::UnsafeArenaSwap(ClassificationResponse* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void ClassificationResponse::InternalSwap(ClassificationResponse* other) {
  std::swap(result_, other->result_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ClassificationResponse::GetMetadata() const {
  protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tensorflow_5fserving_2fapis_2fclassification_2eproto::file_level_metadata[4];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ClassificationResponse

// .tensorflow.serving.ClassificationResult result = 1;
bool ClassificationResponse::has_result() const {
  return this != internal_default_instance() && result_ != NULL;
}
void ClassificationResponse::clear_result() {
  if (GetArenaNoVirtual() == NULL && result_ != NULL) delete result_;
  result_ = NULL;
}
const ::tensorflow::serving::ClassificationResult& ClassificationResponse::result() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.ClassificationResponse.result)
  return result_ != NULL ? *result_
                         : *::tensorflow::serving::ClassificationResult::internal_default_instance();
}
::tensorflow::serving::ClassificationResult* ClassificationResponse::mutable_result() {
  
  if (result_ == NULL) {
    _slow_mutable_result();
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.ClassificationResponse.result)
  return result_;
}
::tensorflow::serving::ClassificationResult* ClassificationResponse::release_result() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.ClassificationResponse.result)
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_result();
  } else {
    ::tensorflow::serving::ClassificationResult* temp = result_;
    result_ = NULL;
    return temp;
  }
}
 void ClassificationResponse::set_allocated_result(::tensorflow::serving::ClassificationResult* result) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete result_;
  }
  if (result != NULL) {
    _slow_set_allocated_result(message_arena, &result);
  }
  result_ = result;
  if (result) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.ClassificationResponse.result)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace serving
}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)
