/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.tensorflow.serving.ModelConfig');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.tensorflow.serving.LoggingConfig');

goog.forwardDeclare('proto.tensorflow.serving.FileSystemStoragePathSourceConfig.VersionPolicy');
goog.forwardDeclare('proto.tensorflow.serving.ModelType');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.serving.ModelConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tensorflow.serving.ModelConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tensorflow.serving.ModelConfig.displayName = 'proto.tensorflow.serving.ModelConfig';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.serving.ModelConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.serving.ModelConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.serving.ModelConfig} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tensorflow.serving.ModelConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    basePath: jspb.Message.getFieldWithDefault(msg, 2, ""),
    modelType: jspb.Message.getFieldWithDefault(msg, 3, 0),
    modelPlatform: jspb.Message.getFieldWithDefault(msg, 4, ""),
    versionPolicy: jspb.Message.getFieldWithDefault(msg, 5, 0),
    loggingConfig: (f = msg.getLoggingConfig()) && proto.tensorflow.serving.LoggingConfig.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.serving.ModelConfig}
 */
proto.tensorflow.serving.ModelConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.serving.ModelConfig;
  return proto.tensorflow.serving.ModelConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.serving.ModelConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.serving.ModelConfig}
 */
proto.tensorflow.serving.ModelConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBasePath(value);
      break;
    case 3:
      var value = /** @type {!proto.tensorflow.serving.ModelType} */ (reader.readEnum());
      msg.setModelType(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setModelPlatform(value);
      break;
    case 5:
      var value = /** @type {!proto.tensorflow.serving.FileSystemStoragePathSourceConfig.VersionPolicy} */ (reader.readEnum());
      msg.setVersionPolicy(value);
      break;
    case 6:
      var value = new proto.tensorflow.serving.LoggingConfig;
      reader.readMessage(value,proto.tensorflow.serving.LoggingConfig.deserializeBinaryFromReader);
      msg.setLoggingConfig(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.serving.ModelConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.serving.ModelConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.serving.ModelConfig} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.tensorflow.serving.ModelConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBasePath();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getModelType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getModelPlatform();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getVersionPolicy();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getLoggingConfig();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.tensorflow.serving.LoggingConfig.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.tensorflow.serving.ModelConfig.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.tensorflow.serving.ModelConfig.prototype.setName = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string base_path = 2;
 * @return {string}
 */
proto.tensorflow.serving.ModelConfig.prototype.getBasePath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.tensorflow.serving.ModelConfig.prototype.setBasePath = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional ModelType model_type = 3;
 * @return {!proto.tensorflow.serving.ModelType}
 */
proto.tensorflow.serving.ModelConfig.prototype.getModelType = function() {
  return /** @type {!proto.tensorflow.serving.ModelType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.tensorflow.serving.ModelType} value */
proto.tensorflow.serving.ModelConfig.prototype.setModelType = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string model_platform = 4;
 * @return {string}
 */
proto.tensorflow.serving.ModelConfig.prototype.getModelPlatform = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.tensorflow.serving.ModelConfig.prototype.setModelPlatform = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional FileSystemStoragePathSourceConfig.VersionPolicy version_policy = 5;
 * @return {!proto.tensorflow.serving.FileSystemStoragePathSourceConfig.VersionPolicy}
 */
proto.tensorflow.serving.ModelConfig.prototype.getVersionPolicy = function() {
  return /** @type {!proto.tensorflow.serving.FileSystemStoragePathSourceConfig.VersionPolicy} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {!proto.tensorflow.serving.FileSystemStoragePathSourceConfig.VersionPolicy} value */
proto.tensorflow.serving.ModelConfig.prototype.setVersionPolicy = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional LoggingConfig logging_config = 6;
 * @return {?proto.tensorflow.serving.LoggingConfig}
 */
proto.tensorflow.serving.ModelConfig.prototype.getLoggingConfig = function() {
  return /** @type{?proto.tensorflow.serving.LoggingConfig} */ (
    jspb.Message.getWrapperField(this, proto.tensorflow.serving.LoggingConfig, 6));
};


/** @param {?proto.tensorflow.serving.LoggingConfig|undefined} value */
proto.tensorflow.serving.ModelConfig.prototype.setLoggingConfig = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.tensorflow.serving.ModelConfig.prototype.clearLoggingConfig = function() {
  this.setLoggingConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tensorflow.serving.ModelConfig.prototype.hasLoggingConfig = function() {
  return jspb.Message.getField(this, 6) != null;
};


