/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.xla.PadRequest');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.xla.ComputationDataHandle');
goog.require('proto.xla.PaddingConfig');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xla.PadRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xla.PadRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.xla.PadRequest.displayName = 'proto.xla.PadRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xla.PadRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.xla.PadRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xla.PadRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.xla.PadRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    operand: (f = msg.getOperand()) && proto.xla.ComputationDataHandle.toObject(includeInstance, f),
    paddingValue: (f = msg.getPaddingValue()) && proto.xla.ComputationDataHandle.toObject(includeInstance, f),
    paddingConfig: (f = msg.getPaddingConfig()) && proto.xla.PaddingConfig.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xla.PadRequest}
 */
proto.xla.PadRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xla.PadRequest;
  return proto.xla.PadRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xla.PadRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xla.PadRequest}
 */
proto.xla.PadRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new proto.xla.ComputationDataHandle;
      reader.readMessage(value,proto.xla.ComputationDataHandle.deserializeBinaryFromReader);
      msg.setOperand(value);
      break;
    case 3:
      var value = new proto.xla.ComputationDataHandle;
      reader.readMessage(value,proto.xla.ComputationDataHandle.deserializeBinaryFromReader);
      msg.setPaddingValue(value);
      break;
    case 4:
      var value = new proto.xla.PaddingConfig;
      reader.readMessage(value,proto.xla.PaddingConfig.deserializeBinaryFromReader);
      msg.setPaddingConfig(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xla.PadRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xla.PadRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xla.PadRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.xla.PadRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOperand();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.xla.ComputationDataHandle.serializeBinaryToWriter
    );
  }
  f = message.getPaddingValue();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.xla.ComputationDataHandle.serializeBinaryToWriter
    );
  }
  f = message.getPaddingConfig();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.xla.PaddingConfig.serializeBinaryToWriter
    );
  }
};


/**
 * optional ComputationDataHandle operand = 2;
 * @return {?proto.xla.ComputationDataHandle}
 */
proto.xla.PadRequest.prototype.getOperand = function() {
  return /** @type{?proto.xla.ComputationDataHandle} */ (
    jspb.Message.getWrapperField(this, proto.xla.ComputationDataHandle, 2));
};


/** @param {?proto.xla.ComputationDataHandle|undefined} value */
proto.xla.PadRequest.prototype.setOperand = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.xla.PadRequest.prototype.clearOperand = function() {
  this.setOperand(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.xla.PadRequest.prototype.hasOperand = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ComputationDataHandle padding_value = 3;
 * @return {?proto.xla.ComputationDataHandle}
 */
proto.xla.PadRequest.prototype.getPaddingValue = function() {
  return /** @type{?proto.xla.ComputationDataHandle} */ (
    jspb.Message.getWrapperField(this, proto.xla.ComputationDataHandle, 3));
};


/** @param {?proto.xla.ComputationDataHandle|undefined} value */
proto.xla.PadRequest.prototype.setPaddingValue = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.xla.PadRequest.prototype.clearPaddingValue = function() {
  this.setPaddingValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.xla.PadRequest.prototype.hasPaddingValue = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional PaddingConfig padding_config = 4;
 * @return {?proto.xla.PaddingConfig}
 */
proto.xla.PadRequest.prototype.getPaddingConfig = function() {
  return /** @type{?proto.xla.PaddingConfig} */ (
    jspb.Message.getWrapperField(this, proto.xla.PaddingConfig, 4));
};


/** @param {?proto.xla.PaddingConfig|undefined} value */
proto.xla.PadRequest.prototype.setPaddingConfig = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.xla.PadRequest.prototype.clearPaddingConfig = function() {
  this.setPaddingConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.xla.PadRequest.prototype.hasPaddingConfig = function() {
  return jspb.Message.getField(this, 4) != null;
};


