/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.tensorflow.Summary');
goog.provide('proto.tensorflow.Summary.Audio');
goog.provide('proto.tensorflow.Summary.Image');
goog.provide('proto.tensorflow.Summary.Value');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.tensorflow.HistogramProto');
goog.require('proto.tensorflow.TensorProto');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.Summary = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tensorflow.Summary.repeatedFields_, null);
};
goog.inherits(proto.tensorflow.Summary, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tensorflow.Summary.displayName = 'proto.tensorflow.Summary';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tensorflow.Summary.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.Summary.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.Summary.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.Summary} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tensorflow.Summary.toObject = function(includeInstance, msg) {
  var f, obj = {
    valueList: jspb.Message.toObjectList(msg.getValueList(),
    proto.tensorflow.Summary.Value.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.Summary}
 */
proto.tensorflow.Summary.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.Summary;
  return proto.tensorflow.Summary.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.Summary} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.Summary}
 */
proto.tensorflow.Summary.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.tensorflow.Summary.Value;
      reader.readMessage(value,proto.tensorflow.Summary.Value.deserializeBinaryFromReader);
      msg.addValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.Summary.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.Summary.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.Summary} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.tensorflow.Summary.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValueList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.tensorflow.Summary.Value.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.Summary.Image = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tensorflow.Summary.Image, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tensorflow.Summary.Image.displayName = 'proto.tensorflow.Summary.Image';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.Summary.Image.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.Summary.Image.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.Summary.Image} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tensorflow.Summary.Image.toObject = function(includeInstance, msg) {
  var f, obj = {
    height: jspb.Message.getFieldWithDefault(msg, 1, 0),
    width: jspb.Message.getFieldWithDefault(msg, 2, 0),
    colorspace: jspb.Message.getFieldWithDefault(msg, 3, 0),
    encodedImageString: msg.getEncodedImageString_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.Summary.Image}
 */
proto.tensorflow.Summary.Image.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.Summary.Image;
  return proto.tensorflow.Summary.Image.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.Summary.Image} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.Summary.Image}
 */
proto.tensorflow.Summary.Image.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHeight(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWidth(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setColorspace(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEncodedImageString(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.Summary.Image.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.Summary.Image.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.Summary.Image} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.tensorflow.Summary.Image.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeight();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getWidth();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getColorspace();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getEncodedImageString_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
};


/**
 * optional int32 height = 1;
 * @return {number}
 */
proto.tensorflow.Summary.Image.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.tensorflow.Summary.Image.prototype.setHeight = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 width = 2;
 * @return {number}
 */
proto.tensorflow.Summary.Image.prototype.getWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.tensorflow.Summary.Image.prototype.setWidth = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int32 colorspace = 3;
 * @return {number}
 */
proto.tensorflow.Summary.Image.prototype.getColorspace = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.tensorflow.Summary.Image.prototype.setColorspace = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional bytes encoded_image_string = 4;
 * @return {string}
 */
proto.tensorflow.Summary.Image.prototype.getEncodedImageString = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes encoded_image_string = 4;
 * This is a type-conversion wrapper around `getEncodedImageString()`
 * @return {string}
 */
proto.tensorflow.Summary.Image.prototype.getEncodedImageString_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEncodedImageString()));
};


/**
 * optional bytes encoded_image_string = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEncodedImageString()`
 * @return {!Uint8Array}
 */
proto.tensorflow.Summary.Image.prototype.getEncodedImageString_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEncodedImageString()));
};


/** @param {!(string|Uint8Array)} value */
proto.tensorflow.Summary.Image.prototype.setEncodedImageString = function(value) {
  jspb.Message.setField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.Summary.Audio = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tensorflow.Summary.Audio, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tensorflow.Summary.Audio.displayName = 'proto.tensorflow.Summary.Audio';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.Summary.Audio.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.Summary.Audio.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.Summary.Audio} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tensorflow.Summary.Audio.toObject = function(includeInstance, msg) {
  var f, obj = {
    sampleRate: +jspb.Message.getFieldWithDefault(msg, 1, 0.0),
    numChannels: jspb.Message.getFieldWithDefault(msg, 2, 0),
    lengthFrames: jspb.Message.getFieldWithDefault(msg, 3, 0),
    encodedAudioString: msg.getEncodedAudioString_asB64(),
    contentType: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.Summary.Audio}
 */
proto.tensorflow.Summary.Audio.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.Summary.Audio;
  return proto.tensorflow.Summary.Audio.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.Summary.Audio} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.Summary.Audio}
 */
proto.tensorflow.Summary.Audio.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSampleRate(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNumChannels(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLengthFrames(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEncodedAudioString(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setContentType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.Summary.Audio.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.Summary.Audio.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.Summary.Audio} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.tensorflow.Summary.Audio.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSampleRate();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getNumChannels();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getLengthFrames();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getEncodedAudioString_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getContentType();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional float sample_rate = 1;
 * @return {number}
 */
proto.tensorflow.Summary.Audio.prototype.getSampleRate = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 1, 0.0));
};


/** @param {number} value */
proto.tensorflow.Summary.Audio.prototype.setSampleRate = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int64 num_channels = 2;
 * @return {number}
 */
proto.tensorflow.Summary.Audio.prototype.getNumChannels = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.tensorflow.Summary.Audio.prototype.setNumChannels = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int64 length_frames = 3;
 * @return {number}
 */
proto.tensorflow.Summary.Audio.prototype.getLengthFrames = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.tensorflow.Summary.Audio.prototype.setLengthFrames = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional bytes encoded_audio_string = 4;
 * @return {string}
 */
proto.tensorflow.Summary.Audio.prototype.getEncodedAudioString = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes encoded_audio_string = 4;
 * This is a type-conversion wrapper around `getEncodedAudioString()`
 * @return {string}
 */
proto.tensorflow.Summary.Audio.prototype.getEncodedAudioString_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEncodedAudioString()));
};


/**
 * optional bytes encoded_audio_string = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEncodedAudioString()`
 * @return {!Uint8Array}
 */
proto.tensorflow.Summary.Audio.prototype.getEncodedAudioString_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEncodedAudioString()));
};


/** @param {!(string|Uint8Array)} value */
proto.tensorflow.Summary.Audio.prototype.setEncodedAudioString = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string content_type = 5;
 * @return {string}
 */
proto.tensorflow.Summary.Audio.prototype.getContentType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.tensorflow.Summary.Audio.prototype.setContentType = function(value) {
  jspb.Message.setField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tensorflow.Summary.Value = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.tensorflow.Summary.Value.oneofGroups_);
};
goog.inherits(proto.tensorflow.Summary.Value, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.tensorflow.Summary.Value.displayName = 'proto.tensorflow.Summary.Value';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.tensorflow.Summary.Value.oneofGroups_ = [[2,3,4,5,6,8]];

/**
 * @enum {number}
 */
proto.tensorflow.Summary.Value.ValueCase = {
  VALUE_NOT_SET: 0,
  SIMPLE_VALUE: 2,
  OBSOLETE_OLD_STYLE_HISTOGRAM: 3,
  IMAGE: 4,
  HISTO: 5,
  AUDIO: 6,
  TENSOR: 8
};

/**
 * @return {proto.tensorflow.Summary.Value.ValueCase}
 */
proto.tensorflow.Summary.Value.prototype.getValueCase = function() {
  return /** @type {proto.tensorflow.Summary.Value.ValueCase} */(jspb.Message.computeOneofCase(this, proto.tensorflow.Summary.Value.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tensorflow.Summary.Value.prototype.toObject = function(opt_includeInstance) {
  return proto.tensorflow.Summary.Value.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tensorflow.Summary.Value} msg The msg instance to transform.
 * @return {!Object}
 */
proto.tensorflow.Summary.Value.toObject = function(includeInstance, msg) {
  var f, obj = {
    nodeName: jspb.Message.getFieldWithDefault(msg, 7, ""),
    tag: jspb.Message.getFieldWithDefault(msg, 1, ""),
    simpleValue: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    obsoleteOldStyleHistogram: msg.getObsoleteOldStyleHistogram_asB64(),
    image: (f = msg.getImage()) && proto.tensorflow.Summary.Image.toObject(includeInstance, f),
    histo: (f = msg.getHisto()) && proto.tensorflow.HistogramProto.toObject(includeInstance, f),
    audio: (f = msg.getAudio()) && proto.tensorflow.Summary.Audio.toObject(includeInstance, f),
    tensor: (f = msg.getTensor()) && proto.tensorflow.TensorProto.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tensorflow.Summary.Value}
 */
proto.tensorflow.Summary.Value.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tensorflow.Summary.Value;
  return proto.tensorflow.Summary.Value.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tensorflow.Summary.Value} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tensorflow.Summary.Value}
 */
proto.tensorflow.Summary.Value.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setNodeName(value);
      break;
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTag(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSimpleValue(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setObsoleteOldStyleHistogram(value);
      break;
    case 4:
      var value = new proto.tensorflow.Summary.Image;
      reader.readMessage(value,proto.tensorflow.Summary.Image.deserializeBinaryFromReader);
      msg.setImage(value);
      break;
    case 5:
      var value = new proto.tensorflow.HistogramProto;
      reader.readMessage(value,proto.tensorflow.HistogramProto.deserializeBinaryFromReader);
      msg.setHisto(value);
      break;
    case 6:
      var value = new proto.tensorflow.Summary.Audio;
      reader.readMessage(value,proto.tensorflow.Summary.Audio.deserializeBinaryFromReader);
      msg.setAudio(value);
      break;
    case 8:
      var value = new proto.tensorflow.TensorProto;
      reader.readMessage(value,proto.tensorflow.TensorProto.deserializeBinaryFromReader);
      msg.setTensor(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tensorflow.Summary.Value.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tensorflow.Summary.Value.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tensorflow.Summary.Value} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.tensorflow.Summary.Value.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNodeName();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getTag();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getImage();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.tensorflow.Summary.Image.serializeBinaryToWriter
    );
  }
  f = message.getHisto();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.tensorflow.HistogramProto.serializeBinaryToWriter
    );
  }
  f = message.getAudio();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.tensorflow.Summary.Audio.serializeBinaryToWriter
    );
  }
  f = message.getTensor();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.tensorflow.TensorProto.serializeBinaryToWriter
    );
  }
};


/**
 * optional string node_name = 7;
 * @return {string}
 */
proto.tensorflow.Summary.Value.prototype.getNodeName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.tensorflow.Summary.Value.prototype.setNodeName = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional string tag = 1;
 * @return {string}
 */
proto.tensorflow.Summary.Value.prototype.getTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.tensorflow.Summary.Value.prototype.setTag = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional float simple_value = 2;
 * @return {number}
 */
proto.tensorflow.Summary.Value.prototype.getSimpleValue = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.tensorflow.Summary.Value.prototype.setSimpleValue = function(value) {
  jspb.Message.setOneofField(this, 2, proto.tensorflow.Summary.Value.oneofGroups_[0], value);
};


proto.tensorflow.Summary.Value.prototype.clearSimpleValue = function() {
  jspb.Message.setOneofField(this, 2, proto.tensorflow.Summary.Value.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tensorflow.Summary.Value.prototype.hasSimpleValue = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bytes obsolete_old_style_histogram = 3;
 * @return {string}
 */
proto.tensorflow.Summary.Value.prototype.getObsoleteOldStyleHistogram = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes obsolete_old_style_histogram = 3;
 * This is a type-conversion wrapper around `getObsoleteOldStyleHistogram()`
 * @return {string}
 */
proto.tensorflow.Summary.Value.prototype.getObsoleteOldStyleHistogram_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getObsoleteOldStyleHistogram()));
};


/**
 * optional bytes obsolete_old_style_histogram = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getObsoleteOldStyleHistogram()`
 * @return {!Uint8Array}
 */
proto.tensorflow.Summary.Value.prototype.getObsoleteOldStyleHistogram_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getObsoleteOldStyleHistogram()));
};


/** @param {!(string|Uint8Array)} value */
proto.tensorflow.Summary.Value.prototype.setObsoleteOldStyleHistogram = function(value) {
  jspb.Message.setOneofField(this, 3, proto.tensorflow.Summary.Value.oneofGroups_[0], value);
};


proto.tensorflow.Summary.Value.prototype.clearObsoleteOldStyleHistogram = function() {
  jspb.Message.setOneofField(this, 3, proto.tensorflow.Summary.Value.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tensorflow.Summary.Value.prototype.hasObsoleteOldStyleHistogram = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Image image = 4;
 * @return {?proto.tensorflow.Summary.Image}
 */
proto.tensorflow.Summary.Value.prototype.getImage = function() {
  return /** @type{?proto.tensorflow.Summary.Image} */ (
    jspb.Message.getWrapperField(this, proto.tensorflow.Summary.Image, 4));
};


/** @param {?proto.tensorflow.Summary.Image|undefined} value */
proto.tensorflow.Summary.Value.prototype.setImage = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.tensorflow.Summary.Value.oneofGroups_[0], value);
};


proto.tensorflow.Summary.Value.prototype.clearImage = function() {
  this.setImage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tensorflow.Summary.Value.prototype.hasImage = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional HistogramProto histo = 5;
 * @return {?proto.tensorflow.HistogramProto}
 */
proto.tensorflow.Summary.Value.prototype.getHisto = function() {
  return /** @type{?proto.tensorflow.HistogramProto} */ (
    jspb.Message.getWrapperField(this, proto.tensorflow.HistogramProto, 5));
};


/** @param {?proto.tensorflow.HistogramProto|undefined} value */
proto.tensorflow.Summary.Value.prototype.setHisto = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.tensorflow.Summary.Value.oneofGroups_[0], value);
};


proto.tensorflow.Summary.Value.prototype.clearHisto = function() {
  this.setHisto(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tensorflow.Summary.Value.prototype.hasHisto = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional Audio audio = 6;
 * @return {?proto.tensorflow.Summary.Audio}
 */
proto.tensorflow.Summary.Value.prototype.getAudio = function() {
  return /** @type{?proto.tensorflow.Summary.Audio} */ (
    jspb.Message.getWrapperField(this, proto.tensorflow.Summary.Audio, 6));
};


/** @param {?proto.tensorflow.Summary.Audio|undefined} value */
proto.tensorflow.Summary.Value.prototype.setAudio = function(value) {
  jspb.Message.setOneofWrapperField(this, 6, proto.tensorflow.Summary.Value.oneofGroups_[0], value);
};


proto.tensorflow.Summary.Value.prototype.clearAudio = function() {
  this.setAudio(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tensorflow.Summary.Value.prototype.hasAudio = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional TensorProto tensor = 8;
 * @return {?proto.tensorflow.TensorProto}
 */
proto.tensorflow.Summary.Value.prototype.getTensor = function() {
  return /** @type{?proto.tensorflow.TensorProto} */ (
    jspb.Message.getWrapperField(this, proto.tensorflow.TensorProto, 8));
};


/** @param {?proto.tensorflow.TensorProto|undefined} value */
proto.tensorflow.Summary.Value.prototype.setTensor = function(value) {
  jspb.Message.setOneofWrapperField(this, 8, proto.tensorflow.Summary.Value.oneofGroups_[0], value);
};


proto.tensorflow.Summary.Value.prototype.clearTensor = function() {
  this.setTensor(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.tensorflow.Summary.Value.prototype.hasTensor = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * repeated Value value = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.tensorflow.Summary.Value>}
 */
proto.tensorflow.Summary.prototype.getValueList = function() {
  return /** @type{!Array.<!proto.tensorflow.Summary.Value>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.tensorflow.Summary.Value, 1));
};


/** @param {!Array.<!proto.tensorflow.Summary.Value>} value */
proto.tensorflow.Summary.prototype.setValueList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.tensorflow.Summary.Value=} opt_value
 * @param {number=} opt_index
 * @return {!proto.tensorflow.Summary.Value}
 */
proto.tensorflow.Summary.prototype.addValue = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.tensorflow.Summary.Value, opt_index);
};


proto.tensorflow.Summary.prototype.clearValueList = function() {
  this.setValueList([]);
};


