/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.xla.VariadicOpRequest');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('proto.xla.ComputationDataHandle');

goog.forwardDeclare('proto.xla.VariadicOperation');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xla.VariadicOpRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.xla.VariadicOpRequest.repeatedFields_, null);
};
goog.inherits(proto.xla.VariadicOpRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.xla.VariadicOpRequest.displayName = 'proto.xla.VariadicOpRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.xla.VariadicOpRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xla.VariadicOpRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.xla.VariadicOpRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xla.VariadicOpRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.xla.VariadicOpRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    varop: jspb.Message.getFieldWithDefault(msg, 2, 0),
    operandsList: jspb.Message.toObjectList(msg.getOperandsList(),
    proto.xla.ComputationDataHandle.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xla.VariadicOpRequest}
 */
proto.xla.VariadicOpRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xla.VariadicOpRequest;
  return proto.xla.VariadicOpRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xla.VariadicOpRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xla.VariadicOpRequest}
 */
proto.xla.VariadicOpRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {!proto.xla.VariadicOperation} */ (reader.readEnum());
      msg.setVarop(value);
      break;
    case 3:
      var value = new proto.xla.ComputationDataHandle;
      reader.readMessage(value,proto.xla.ComputationDataHandle.deserializeBinaryFromReader);
      msg.addOperands(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xla.VariadicOpRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xla.VariadicOpRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xla.VariadicOpRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.xla.VariadicOpRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVarop();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getOperandsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.xla.ComputationDataHandle.serializeBinaryToWriter
    );
  }
};


/**
 * optional VariadicOperation varop = 2;
 * @return {!proto.xla.VariadicOperation}
 */
proto.xla.VariadicOpRequest.prototype.getVarop = function() {
  return /** @type {!proto.xla.VariadicOperation} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.xla.VariadicOperation} value */
proto.xla.VariadicOpRequest.prototype.setVarop = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated ComputationDataHandle operands = 3;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.xla.ComputationDataHandle>}
 */
proto.xla.VariadicOpRequest.prototype.getOperandsList = function() {
  return /** @type{!Array.<!proto.xla.ComputationDataHandle>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.xla.ComputationDataHandle, 3));
};


/** @param {!Array.<!proto.xla.ComputationDataHandle>} value */
proto.xla.VariadicOpRequest.prototype.setOperandsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.xla.ComputationDataHandle=} opt_value
 * @param {number=} opt_index
 * @return {!proto.xla.ComputationDataHandle}
 */
proto.xla.VariadicOpRequest.prototype.addOperands = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.xla.ComputationDataHandle, opt_index);
};


proto.xla.VariadicOpRequest.prototype.clearOperandsList = function() {
  this.setOperandsList([]);
};


