# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_serving/resources/resources.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tensorflow.serving.Resource" do
    optional :device, :string, 1
    optional :device_instance, :message, 2, "google.protobuf.UInt32Value"
    optional :kind, :string, 3
  end
  add_message "tensorflow.serving.ResourceAllocation" do
    repeated :resource_quantities, :message, 1, "tensorflow.serving.ResourceAllocation.Entry"
  end
  add_message "tensorflow.serving.ResourceAllocation.Entry" do
    optional :resource, :message, 1, "tensorflow.serving.Resource"
    optional :quantity, :uint64, 2
  end
end

module Tensorflow
  module Serving
    Resource = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.serving.Resource").msgclass
    ResourceAllocation = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.serving.ResourceAllocation").msgclass
    ResourceAllocation::Entry = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.serving.ResourceAllocation.Entry").msgclass
  end
end
