// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: tensorflow_serving/servables/tensorflow/saved_model_bundle_source_adapter.proto
#ifndef GRPC_tensorflow_5fserving_2fservables_2ftensorflow_2fsaved_5fmodel_5fbundle_5fsource_5fadapter_2eproto__INCLUDED
#define GRPC_tensorflow_5fserving_2fservables_2ftensorflow_2fsaved_5fmodel_5fbundle_5fsource_5fadapter_2eproto__INCLUDED

#include "tensorflow_serving/servables/tensorflow/saved_model_bundle_source_adapter.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace tensorflow {
namespace serving {

}  // namespace serving
}  // namespace tensorflow


#endif  // GRPC_tensorflow_5fserving_2fservables_2ftensorflow_2fsaved_5fmodel_5fbundle_5fsource_5fadapter_2eproto__INCLUDED
