// Code generated by protoc-gen-go.
// source: serving/tensorflow_serving/config/log_collector_config.proto
// DO NOT EDIT!

/*
Package tensorflow_serving is a generated protocol buffer package.

It is generated from these files:
	serving/tensorflow_serving/config/log_collector_config.proto

It has these top-level messages:
	LogCollectorConfig
*/
package tensorflow_serving

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogCollectorConfig struct {
	// Identifies the type of the LogCollector we will use to collect these logs.
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	// The prefix to use for the filenames of the logs.
	FilenamePrefix string `protobuf:"bytes,2,opt,name=filename_prefix,json=filenamePrefix" json:"filename_prefix,omitempty"`
}

func (m *LogCollectorConfig) Reset()                    { *m = LogCollectorConfig{} }
func (m *LogCollectorConfig) String() string            { return proto.CompactTextString(m) }
func (*LogCollectorConfig) ProtoMessage()               {}
func (*LogCollectorConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LogCollectorConfig) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LogCollectorConfig) GetFilenamePrefix() string {
	if m != nil {
		return m.FilenamePrefix
	}
	return ""
}

func init() {
	proto.RegisterType((*LogCollectorConfig)(nil), "tensorflow.serving.LogCollectorConfig")
}

func init() {
	proto.RegisterFile("serving/tensorflow_serving/config/log_collector_config.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x29, 0x4e, 0x2d, 0x2a,
	0xcb, 0xcc, 0x4b, 0xd7, 0x2f, 0x49, 0xcd, 0x2b, 0xce, 0x2f, 0x4a, 0xcb, 0xc9, 0x2f, 0x8f, 0x87,
	0x09, 0x25, 0xe7, 0xe7, 0xa5, 0x65, 0xa6, 0xeb, 0xe7, 0xe4, 0xa7, 0xc7, 0x27, 0xe7, 0xe7, 0xe4,
	0xa4, 0x26, 0x97, 0xe4, 0x17, 0xc5, 0x43, 0x04, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x84,
	0x10, 0xba, 0xf4, 0xa0, 0xba, 0x94, 0x02, 0xb9, 0x84, 0x7c, 0xf2, 0xd3, 0x9d, 0x61, 0x1a, 0x9c,
	0xc1, 0xea, 0x85, 0x84, 0xb8, 0x58, 0x4a, 0x2a, 0x0b, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0xc0, 0x6c, 0x21, 0x75, 0x2e, 0xfe, 0xb4, 0xcc, 0x9c, 0xd4, 0xbc, 0xc4, 0xdc, 0xd4, 0xf8,
	0x82, 0xa2, 0xd4, 0xb4, 0xcc, 0x0a, 0x09, 0x26, 0xb0, 0x34, 0x1f, 0x4c, 0x38, 0x00, 0x2c, 0xea,
	0xc4, 0xfc, 0x83, 0x91, 0x31, 0x89, 0x0d, 0x6c, 0xa5, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xdf,
	0xaf, 0x54, 0x2f, 0xb2, 0x00, 0x00, 0x00,
}
